### PR TITLE
Scan classpath for service (API) classes listed in @WebService annotations

### PR DESCRIPTION
**Pull request by medvedev**
Support for Servlet 3.0
Scan project sources for @WebService-annotated endpoints servlets (child classes of EndpointsServlet) and add found API classes (listed in servlet init param named "services") to docs\libs generated by endpoints plugin.

### CODE REVIEW

**Comment by medvedev** [comment]
This is a copy of #60, with some dedpulication removed, as requested by @loosebazooka

**Comment by loosebazooka** [comment]
@tangiel does the endpoints framework server side make all `@webservice` annotated classes accessible as endpoints?

**Comment by medvedev** [comment]
@loosebazooka, let me answer.
Answer is: not really. But once servlet that extends EndpointServlet has class names in "services" init param, these services are available as APIs.
IMO, it should have no matter, if endpoints are configured through web.xml or @WebService annotations.

**Comment by tangiel** [comment]
Can you give a short example of what you're doing that needs this?

**Comment by loosebazooka** [comment]
@medvedev I'm more concerned with how the backend deals with these annotations. If the have a scanner already, then we can re-use that. No point in re-implementing this everywhere.

**Comment by loosebazooka** [comment]
@medvedev we're still discussing this. We're trying to determine what the best mechanism for this should be, given that extending the EndpointsServlet at first glance seems like an odd design pattern.

**Pull request closed without merging**
